package com.ping23.scratch.gson.nested;

public class ExampleJsonResponses {
    
    public static final String BINDINGS = "["
            + "        {"
            + "            \"roleType\": \"Event Code\","
            + "            \"resourceName\": \"1A\","
            + "            \"modifiedBy\": \"Jim\""
            + "        },"
            + "        {"
            + "            \"roleType\": \"Squeeze Profile\","
            + "            \"resourceName\": \"YES\","
            + "            \"modifiedBy\": \"Jim\""
            + "        }"
            + "    ]";

    public static final String EVENTS = "["
            + "        {"
            + "            \"eventId\": 1,"
            + "            \"segmentType\": \"S\","
            + "            \"duration\": 1800,"
            + "            \"offset\": 0,"
            + "            \"className\": \"com.nbc.genesis.data.BlackEvent\","
            + "            \"overrun\": 0,"
            + "            \"modifiedBy\": null,"
            + "            \"createdBy\": null,"
            + "            \"createdAt\": \"2022-03-03T17:51:55.043292Z\","
            + "            \"updatedBy\": null,"
            + "            \"updatedAt\": \"2022-03-03T17:51:55.066456Z\","
            + "            \"children\": [],"
            + "            \"bindings\": ["
            + "                {"
            + "                    \"roleType\": \"Event Code\","
            + "                    \"resourceName\": \"SH\","
            + "                    \"modifiedBy\": \"Jim\""
            + "                },"
            + "                {"
            + "                    \"roleType\": \"Event Process Type\","
            + "                    \"resourceName\": \"SH\","
            + "                    \"modifiedBy\": \"Jim\""
            + "                },"
            + "                {"
            + "                    \"roleType\": \"Event Title\","
            + "                    \"resourceName\": \"Black\","
            + "                    \"modifiedBy\": \"Jim\""
            + "                }"
            + "            ]"
            + "        },"
            + "        {"
            + "            \"eventId\": 2,"
            + "            \"segmentType\": \"S\","
            + "            \"duration\": 0,"
            + "            \"offset\": 0,"
            + "            \"className\": \"com.nbc.genesis.data.GPIGroupEvent\","
            + "            \"overrun\": null,"
            + "            \"modifiedBy\": \"Jim\","
            + "            \"createdBy\": null,"
            + "            \"createdAt\": \"2022-03-03T17:51:55.058096Z\","
            + "            \"updatedBy\": null,"
            + "            \"updatedAt\": \"2022-03-03T17:51:55.066717Z\","
            + "            \"children\": ["
            + "                {"
            + "                    \"eventId\": 3,"
            + "                    \"segmentType\": \"S\","
            + "                    \"duration\": 30,"
            + "                    \"offset\": 0,"
            + "                    \"className\": \"com.nbc.genesis.data.GPIEvent\","
            + "                    \"overrun\": null,"
            + "                    \"modifiedBy\": \"Jim\","
            + "                    \"createdBy\": null,"
            + "                    \"createdAt\": \"2022-03-03T17:51:55.060990Z\","
            + "                    \"updatedBy\": null,"
            + "                    \"updatedAt\": \"2022-03-03T17:51:55.066948Z\","
            + "                    \"children\": [],"
            + "                    \"bindings\": ["
            + "                        {"
            + "                            \"roleType\": \"Event Code\","
            + "                            \"resourceName\": \"SH\","
            + "                            \"modifiedBy\": \"Jim\""
            + "                        },"
            + "                        {"
            + "                            \"roleType\": \"Event Process Type\","
            + "                            \"resourceName\": \"SH\","
            + "                            \"modifiedBy\": \"Jim\""
            + "                        },"
            + "                        {"
            + "                            \"roleType\": \"Event Title\","
            + "                            \"resourceName\": \"ProgramStart\","
            + "                            \"modifiedBy\": \"Jim\""
            + "                        },"
            + "                        {"
            + "                            \"roleType\": \"GPI Action Mode\","
            + "                            \"resourceName\": \"ON\","
            + "                            \"modifiedBy\": \"Jim\""
            + "                        },"
            + "                        {"
            + "                            \"roleType\": \"GPI Resource Name\","
            + "                            \"resourceName\": \"ProgramStart\","
            + "                            \"modifiedBy\": \"Jim\""
            + "                        },"
            + "                        {"
            + "                            \"roleType\": \"Offset From End\","
            + "                            \"resourceName\": \"N\","
            + "                            \"modifiedBy\": \"Jim\""
            + "                        }"
            + "                    ]"
            + "                }"
            + "            ],"
            + "            \"bindings\": ["
            + "                {"
            + "                    \"roleType\": \"Event Code\","
            + "                    \"resourceName\": \"SH\","
            + "                    \"modifiedBy\": \"Jim\""
            + "                },"
            + "                {"
            + "                    \"roleType\": \"Event Process Type\","
            + "                    \"resourceName\": \"SH\","
            + "                    \"modifiedBy\": \"Jim\""
            + "                },"
            + "                {"
            + "                    \"roleType\": \"Event Title\","
            + "                    \"resourceName\": \"Program Start\","
            + "                    \"modifiedBy\": \"Jim\""
            + "                },"
            + "                {"
            + "                    \"roleType\": \"GPI Group Name\","
            + "                    \"resourceName\": \"Program Start\","
            + "                    \"modifiedBy\": \"Jim\""
            + "                }"
            + "            ]"
            + "        }"
            + "    ]";
    
    public static final String ONE = "{"
            + "    \"name\": \"01CalculatingFrog01\","
            + "    \"programOriginator\": 12,"
            + "    \"networkName\": null,"
            + "    \"className\": \"com.nbc.genesis.data.BlackEvent\","
            + "    \"readOnly\": true,"
            + "    \"deleteIndicator\": false,"
            + "    \"duration\": 90000,"
            + "    \"embedIndicator\": \"Y\","
            + "    \"salesReleaseIndicator\": \"Y\","
            + "    \"usedOn\": null,"
            + "    \"deleteDate\": null,"
            + "    \"modifiedAt\": 12345678,"
            + "    \"modifiedBy\": null,"
            + "    \"bindings\": [],"
            + "    \"events\": [],"
            + "    \"createdBy\": \"Cedric Baumbach\","
            + "    \"createdAt\": \"2022-04-12T11:22:35.087Z\","
            + "    \"updatedBy\": \"Faye Hudson\","
            + "    \"updatedAt\": \"2022-04-12T11:22:35.087Z\""
            + "}";
    
    public static final String TWO = "{"
            + "    \"name\": \"01doloribus01\","
            + "    \"embedIndicator\": \"N\","
            + "    \"salesReleaseIndicator\": \"Y\","
            + "    \"deleteIndicator\": false,"
            + "    \"bindings\": " + BINDINGS + ","
            + "    \"programOriginator\": 3,"
            + "    \"duration\": 90000,"
            + "    \"className\": \"com.nbc.genesis.data.BlackEvent\","
            + "    \"readOnly\": true,"
            + "    \"createdBy\": \"Philip Gislason\""
            + "}";
    
    public static final String THREE = "{"
            + "    \"name\": \"01quasi01\","
            + "    \"programOriginator\": 3,"
            + "    \"networkName\": null,"
            + "    \"className\": \"com.nbc.genesis.data.BlackEvent\","
            + "    \"readOnly\": false,"
            + "    \"deleteIndicator\": false,"
            + "    \"duration\": 90000,"
            + "    \"embedIndicator\": \"N\","
            + "    \"salesReleaseIndicator\": \"Y\","
            + "    \"usedOn\": null,"
            + "    \"deleteDate\": null,"
            + "    \"modifiedAt\": null,"
            + "    \"modifiedBy\": null,"
            + "    \"bindings\": " + BINDINGS + ","
            + "    \"events\": " + EVENTS + ","
            + "    \"createdBy\": \"Monica Jerde PhD\","
            + "    \"createdAt\": \"2022-04-12T16:55:14.681Z\","
            + "    \"updatedBy\": null,"
            + "    \"updatedAt\": \"2022-04-12T16:55:14.681Z\""
            + "}";
    
    public static final String LIST = "["
            + "    {"
            + "        \"name\": \"01ut01\","
            + "        \"programOriginator\": 3,"
            + "        \"networkName\": null,"
            + "        \"className\": \"com.nbc.genesis.data.BlackEvent\","
            + "        \"readOnly\": true,"
            + "        \"deleteIndicator\": false,"
            + "        \"duration\": 90000,"
            + "        \"embedIndicator\": \"Y\","
            + "        \"salesReleaseIndicator\": \"Y\","
            + "        \"usedOn\": null,"
            + "        \"deleteDate\": null,"
            + "        \"modifiedAt\": 12345678,"
            + "        \"modifiedBy\": null,"
            + "        \"bindings\": " + BINDINGS + ","
            + "        \"events\": " + EVENTS + ","
            + "        \"createdBy\": \"Dr. Deborah Aufderhar\","
            + "        \"createdAt\": \"2022-04-12T11:20:11.756Z\","
            + "        \"updatedBy\": \"Ms. Lana Quitzon\","
            + "        \"updatedAt\": \"2022-04-12T11:20:11.756Z\""
            + "    },"
            + "    {"
            + "        \"name\": \"01cupiditate01\","
            + "        \"programOriginator\": 3,"
            + "        \"networkName\": null,"
            + "        \"className\": \"com.nbc.genesis.data.BlackEvent\","
            + "        \"readOnly\": true,"
            + "        \"deleteIndicator\": false,"
            + "        \"duration\": 90000,"
            + "        \"embedIndicator\": \"Y\","
            + "        \"salesReleaseIndicator\": \"Y\","
            + "        \"usedOn\": null,"
            + "        \"deleteDate\": null,"
            + "        \"modifiedAt\": 12345678,"
            + "        \"modifiedBy\": null,"
            + "        \"bindings\": [],"
            + "        \"events\": [],"
            + "        \"createdBy\": \"Pat Simonis\","
            + "        \"createdAt\": \"2022-04-12T11:21:44.589Z\","
            + "        \"updatedBy\": \"Dolores Williamson\","
            + "        \"updatedAt\": \"2022-04-12T11:21:44.589Z\""
            + "    },"
            + "    {"
            + "        \"name\": \"01esse01\","
            + "        \"programOriginator\": 12,"
            + "        \"networkName\": null,"
            + "        \"className\": \"com.nbc.genesis.data.BlackEvent\","
            + "        \"readOnly\": true,"
            + "        \"deleteIndicator\": false,"
            + "        \"duration\": 90000,"
            + "        \"embedIndicator\": \"Y\","
            + "        \"salesReleaseIndicator\": \"Y\","
            + "        \"usedOn\": null,"
            + "        \"deleteDate\": null,"
            + "        \"modifiedAt\": 12345678,"
            + "        \"modifiedBy\": null,"
            + "        \"bindings\": [],"
            + "        \"events\": [],"
            + "        \"createdBy\": \"Cedric Baumbach\","
            + "        \"createdAt\": \"2022-04-12T11:22:35.087Z\","
            + "        \"updatedBy\": \"Faye Hudson\","
            + "        \"updatedAt\": \"2022-04-12T11:22:35.087Z\""
            + "    }"
            + "]";
}
